/// Flutter icons Navigation_Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navigation_Icons
///      fonts:
///       - asset: fonts/Navigation_Icons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

// ignore: camel_case_types
class Navigation_Icons {
  Navigation_Icons._();

  static const _kFontFam = 'Navigation_Icons';
  static const String? _kFontPkg = null;

  static const IconData cartsvg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fvtsvg = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exploresvg = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storesvg = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fvtsvg2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountsvg2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountsvg = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
